/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgrammaRouteImport } from './routes/programma'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as OverRouteImport } from './routes/over'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArchiefRouteImport } from './routes/archief'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgrammaSlugRouteImport } from './routes/programma.$slug'

const ProgrammaRoute = ProgrammaRouteImport.update({
  id: '/programma',
  path: '/programma',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const OverRoute = OverRouteImport.update({
  id: '/over',
  path: '/over',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiefRoute = ArchiefRouteImport.update({
  id: '/archief',
  path: '/archief',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammaSlugRoute = ProgrammaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgrammaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archief': typeof ArchiefRoute
  '/contact': typeof ContactRoute
  '/over': typeof OverRoute
  '/platform': typeof PlatformRoute
  '/programma': typeof ProgrammaRouteWithChildren
  '/programma/$slug': typeof ProgrammaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archief': typeof ArchiefRoute
  '/contact': typeof ContactRoute
  '/over': typeof OverRoute
  '/platform': typeof PlatformRoute
  '/programma': typeof ProgrammaRouteWithChildren
  '/programma/$slug': typeof ProgrammaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archief': typeof ArchiefRoute
  '/contact': typeof ContactRoute
  '/over': typeof OverRoute
  '/platform': typeof PlatformRoute
  '/programma': typeof ProgrammaRouteWithChildren
  '/programma/$slug': typeof ProgrammaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archief'
    | '/contact'
    | '/over'
    | '/platform'
    | '/programma'
    | '/programma/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archief'
    | '/contact'
    | '/over'
    | '/platform'
    | '/programma'
    | '/programma/$slug'
  id:
    | '__root__'
    | '/'
    | '/archief'
    | '/contact'
    | '/over'
    | '/platform'
    | '/programma'
    | '/programma/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiefRoute: typeof ArchiefRoute
  ContactRoute: typeof ContactRoute
  OverRoute: typeof OverRoute
  PlatformRoute: typeof PlatformRoute
  ProgrammaRoute: typeof ProgrammaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programma': {
      id: '/programma'
      path: '/programma'
      fullPath: '/programma'
      preLoaderRoute: typeof ProgrammaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over': {
      id: '/over'
      path: '/over'
      fullPath: '/over'
      preLoaderRoute: typeof OverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archief': {
      id: '/archief'
      path: '/archief'
      fullPath: '/archief'
      preLoaderRoute: typeof ArchiefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programma/$slug': {
      id: '/programma/$slug'
      path: '/$slug'
      fullPath: '/programma/$slug'
      preLoaderRoute: typeof ProgrammaSlugRouteImport
      parentRoute: typeof ProgrammaRoute
    }
  }
}

interface ProgrammaRouteChildren {
  ProgrammaSlugRoute: typeof ProgrammaSlugRoute
}

const ProgrammaRouteChildren: ProgrammaRouteChildren = {
  ProgrammaSlugRoute: ProgrammaSlugRoute,
}

const ProgrammaRouteWithChildren = ProgrammaRoute._addFileChildren(
  ProgrammaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiefRoute: ArchiefRoute,
  ContactRoute: ContactRoute,
  OverRoute: OverRoute,
  PlatformRoute: PlatformRoute,
  ProgrammaRoute: ProgrammaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
